### ISSUE TITLE
Valores de campos faltando na requisição PUT da entidade alunos

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#10]
Olá,

Por favor, adicionar os seguintes campos e atualizar a documentação da entidade alunos.
Uma utiliza 0 e a outra -1 por convenção do próprio MEC.

```
cor = 0
Não declarada

grau_responsavel = -1
Não Informado
```

**Comment by umarley** [comment]
@marcosroriz informações adicionadas conforme solicitada, documentação no swagger também atualizada.
