### ISSUE TITLE
Módulo escolas - GET - Obter todos os alunos de uma escola

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#102]
![image](https://user-images.githubusercontent.com/45390353/187096630-36d10411-8005-49a7-8cef-94b1393fa037.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/5201405/22046194/alunos
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Existem campos de cpf nulos e os campos de loc_latitude e loc_longitude estão nulos, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187096683-ed84dc7d-11d2-4248-86a9-c7d25c755b2e.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/5201405/22046194/aluno
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ result: "true", messages: “string” }
•	Retornou 200 e com erro, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187096695-fb27bdb7-c23d-4cfd-b566-85d9768f7b31.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/5201405/0/alunos
Resultado:
•	Retorno do HTTP é 404 – Not found
•	Não está documentado na API
•	Está usando o seguinte formato 
{ ..., total: 0, result: "false"}
•	Teria que retornar alguma mensagem de erro, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187096702-d991e6b8-9198-4c62-a430-5ce548064ca1.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/0/22046194/alunos
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{ result: "false", messages: “string”}
![image](https://user-images.githubusercontent.com/45390353/187096707-ea417024-1554-481c-8e9f-e47e9afe5bd2.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/escolas/111111111111111111/22046194/alunos
Resultado:
•	Retorno do HTTP é 404 – Not found
•	Não está documentado na API
•	Está usando o seguinte formato 
{ result: "false", messages: “string”}
![image](https://user-images.githubusercontent.com/45390353/187096714-00be8eb0-7f0a-4837-9f8c-b606ddebac8d.png)

**Comment by umarley** [comment]
API revisada e documentação atualizada.
