### ISSUE TITLE
Módulo monitores - GET - Obter lista de monitores de um município

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#104]
![image](https://user-images.githubusercontent.com/45390353/187096914-d1bf069c-51f4-4cdb-bc93-98bdf91148e3.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/5201405
Resultado:
•	Retorno do HTTP está 200 (OK)
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Possui links, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187096946-7851c389-b1a3-41d4-b2cf-3451e18fd35e.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/0
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187096962-ed00194e-8bd1-4673-afc5-2c894d7d0cbc.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/monitores/ 111111111111111111111111111
Resultado:
•	Retorno do HTTP é 404 – Not found
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }

![image](https://user-images.githubusercontent.com/45390353/187096975-4794c0af-d87d-4541-a02e-748a9eb95a5f.png)

**Comment by nataliasou** [comment]
@umarley 
Obs. não coloquei o "_links"
```
get:
      tags:
      - monitores
      summary: Obter a lista de monitores de um município
      operationId: getMonitores
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que o monitor pertence
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/allMonitores'
        400:
          description: Parâmetros incorretos
        403:
          description: Usuário sem permissão para acessar o município selecionado.
      security:
      - api_key: []
```

Models:

```
allMonitores:
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/DadosMonitores'
      total:
        type: integer
      result:
        type: boolean
  DadosMonitores:
    type: object
    properties:
      codigo_cidade: 
        type: integer
      cpf:
        type: string
      nome:
        type: string
      telefone:
        type: string
      data_nascimento:
        description: Data de nascimento no formato dd/mm/yyyy
        type: string
      turno_manha:
        type: string
        description: Trabalha no turno da manhã? S = Sim N = Não
        enum:
        - S
        - N
      turno_tarde:
        type: string
        description: Trabalha no turno da tarde? S = Sim N = Não
        enum:
        - S
        - N
      turno_noite:
        type: string
        description: Trabalha no turno da noite? S = Sim N = Não
        enum:
        - S
        - N
 ```

**Comment by umarley** [comment]
API revisada e documentação atualizada
