### ISSUE TITLE
Módulo monitores - GET - Obter rotas associadas ao monitor

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#106]
![image](https://user-images.githubusercontent.com/45390353/187097308-746f6b12-408e-423f-970f-2f30c12398f6.png)
Não consegui testar.
Mesmo adicionando uma rota ao monitor ou até mesmo se passar um valor de cpf que não está cadastrado, retorna:
{
    "data": [],
    "total": 0,
    "result": false
}

**Comment by umarley** [comment]
Atualizadas as descrições da documentação
