### ISSUE TITLE
Módulo garagens - GET - Obter a lista de garagens de um município

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#107]
![image](https://user-images.githubusercontent.com/45390353/187097492-516ee469-c4cb-4ce2-b78f-4214ac4df41c.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/garagens/5201405
Resultado:
•	Retorno do HTTP é 200 (OK)
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Retorna links, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187097501-4a700dd1-c4e2-4295-95c6-4b724fd782d9.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/garagens/0
Resultado:
•	Retorno do HTTP é 400 – Bad request
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{result: "false", “messages”: “string”}
![image](https://user-images.githubusercontent.com/45390353/187097622-a3a887f4-fb88-4c8c-84a1-e019ccc8a723.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/garagens/1111111111111
Resultado:
•	Retorno do HTTP é 404 – Not found
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{result: "false", “messages”: “string”}

![image](https://user-images.githubusercontent.com/45390353/187097628-c353978d-1d2a-49f4-8520-4bd7c4f26679.png)

**Comment by nataliasou** [comment]
@umarley 
Obs. Não coloquei o "_links"

```
get:
      tags:
      - garagens
      summary: Obter a lista de garagens de um município
      operationId: getGaragens
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a garagem pertence.
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/allGaragens'
        400:
          description: Parâmetros incorretos
        403:
          description: Usuário sem permissão para acessar o município selecionado.
      security:
      - api_key: []
```
Model:

```
allGaragens:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            nome:
              type: string
            codigo_cidade:
              type: integer
            id_garagem:
              type: integer
            loc_cep:
              type: string
      total:
        type: integer
      result:
        type: boolean
```

**Comment by umarley** [comment]
API revisada e documentação atualizada
