### ISSUE TITLE
Módulo ordemServico - GET - Obter dados de uma ordem de serviço específica

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#110]
![image](https://user-images.githubusercontent.com/45390353/187098243-20329df7-2b37-49f6-b2df-b9aa495e23ae.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/ordens-servicos/5201405/1372
Resultado:
•	Retorno do HTTP é 200 - Ok
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ ..., result: "true" }
•	Possui links, não possui id da firebase, verificar se isso está correto

![image](https://user-images.githubusercontent.com/45390353/187098248-ec311c36-1af0-4b51-a4f4-7164734dae1f.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/ordens-servicos/5201405/0
Resultado:
•	Retorno do HTTP é 404 – Not found
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ ..., result: "false" }
•	Possui links, não possui mensagem de erro, verificar se isso está correto

![image](https://user-images.githubusercontent.com/45390353/187098276-49e3ad55-800c-40b1-a1ce-6e0477e8b0d7.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/ordens-servicos/0/1372
Resultado:
•	Retorno do HTTP é 404 – Not found
•	O resultado não está documentado na API
•	Está usando o seguinte formato 
{ ..., result: "false" }
![image](https://user-images.githubusercontent.com/45390353/187098287-8f2b50f7-faee-43f0-81d2-44018b8fdd83.png)

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - ordemServico
      summary: Obter dados de uma ordem de serviço específica
      operationId: getOrdemServicoId
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a ordem de serviço pertence
        required: true
        type: integer
      - in: path
        name: id_ordem
        description: ID da ordem que se deseja consultar 
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/OrdemServicoEspecifica'
        404:
          description: Recurso não encontrado.
      security:
      - api_key: []
```

Model:

```
OrdemServicoEspecifica:
    type: object
    properties:
      codigo_cidade:
        type: integer
      id_fornecedor:
        type: integer
      id_veiculo:
        type: integer
      termino:
        type: string
      data:
        type: string
        description: Data da Ordem de serviço no formato dd/mm/yyyy
      tipo_servico:
        type: integer
        description: Tipo do serviço 1. Combustível 2. Lubrificante 3. Pag. Seguro 4. Man. Preventiva 5. Manutenção 
        enum:
          - 1
          - 2
          - 3
          - 4
          - 5
      comentario:
        type: string
      id_ordem:
        type: integer
      id_firebase:
        type: integer
      result:
        type: boolean
```

**Comment by umarley** [comment]
API revisada e documentação atualizada
