### ISSUE TITLE
Módulo normas - GET - Obter dados de uma norma específica

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#113]
![image](https://user-images.githubusercontent.com/45390353/187098731-5ebb9507-c8ee-4f9d-a462-c81f11e28c9d.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405/1
Resultado:
•	Retorno do HTTP é 200 (OK)
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
•	{ ...,result: "true" }

![image](https://user-images.githubusercontent.com/45390353/187098743-be2a1d2a-1e04-4217-913e-9d81288d84f6.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405/11111111111
Resultado:
•	Retorno do HTTP é 500 – Internal Server error, quando coloca um id de norma que não existe.
•	O resultado não está na documentação da API
•	Não possui um formato padronizado
![image](https://user-images.githubusercontent.com/45390353/187099267-942cc294-968f-4821-9837-551cc67ced0e.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/assuntos
Resultado:
•	Retorno do HTTP é 200 (OK)
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
•	{ result: false, “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187099292-8576e4d6-34c0-4fc4-b1d9-5e64bd69ecab.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
get:
      tags:
      - normas
      summary: Obter dados de uma norma específica
      operationId: getNormaId
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código do municipio que a norma pertence.
        required: true
        type: integer
      - in: path
        name: id_norma
        description: ID da norma que se deseja consultar
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/NormaEspecifica'
        500:
          description: Internal Server Error.
      security:
      - api_key: []
```
Model:
```yaml
 NormaEspecifica:
    type: object
    properties:
      id:
        type: integer
      titulo:
        type: string
      id_tipo:
        type: integer
      tipo_veiculo:
        type: integer
      outro_tipo:
        type: integer
      codigo_cidade:
        type: integer
      data_norma:
        type: string
        description: Data da norma no formato dd/mm/yyyy
      assuntos:
        type: array
        items:
          type: string
      result:
        type: boolean
```

**Comment by umarley** [comment]
API revisada e documentação atualizada
