### ISSUE TITLE
Módulo normas - GET - Retorna a relação de assuntos para serem utilizados no cadastro de normas

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#114]
![image](https://user-images.githubusercontent.com/45390353/187099319-4ef7f19c-35f2-4ef4-a737-eebca0c6f5bc.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/assuntos
Resultado:
•	Retorno do HTTP é 200 (OK)
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
•	{ ..., “total”: 0, result: "true" }

![image](https://user-images.githubusercontent.com/45390353/187099348-3876cfbb-457f-4fcd-8146-5a345d6a5759.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/assunts
Resultado:
•	Retorno do HTTP é 500 – Internal Server Error
•	O resultado está diferente do esperado na API
•	Não retorna mensagem de erro padronizada

![image](https://user-images.githubusercontent.com/45390353/187099383-20b19ec5-2724-425b-8ced-14fe78924ade.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
get:
      tags:
      - normas
      summary: Retorna a relação de assuntos para serem utilizados no cadastro de normas
      description: Retorna a relação de assuntos para serem utilizados no cadastro de normas
      produces:
      - application/json
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/NormaAssunto'
        500:
          description: Internal Server Error.
      security:
      - api_key: []
 ```

Model:

```yaml
NormaAssunto:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id_assunto:
              type: integer
            assunto:
              type: string
      total:
        type: integer
      result:
        type: boolean
```

**Comment by umarley** [comment]
API revisada e documentação atualizada
