### ISSUE TITLE
Módulo normas - GET - Retorna a relação de tipos para serem utilizados no cadastro de normas

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#115]
![image](https://user-images.githubusercontent.com/45390353/187099459-124d2b1f-5601-4d43-9da7-2b03bde09f7b.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/tipos
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
•	{ ..., “total”: 0, result: "true" }
![image](https://user-images.githubusercontent.com/45390353/187099472-b6675bb7-86a6-4fed-835e-0d3c8548e5c1.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/tips
Resultado:
•	Retorno do HTTP está 500 – Internal Server Error
•	O resultado não está na documentação da api
•	Não possui um formato padronizado
![image](https://user-images.githubusercontent.com/45390353/187099495-b7e45ce9-38f2-4d1d-b233-e485f7bf6007.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
get:
      tags:
      - normas
      summary: Retorna a relação de tipos para serem utilizados no cadastro de normas
      description: Retorna a relação de tipos para serem utilizados no cadastro de normas
      produces:
      - application/json
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/NormaTipo'
        500:
          description: Internal Server Error.
      security:
      - api_key: []
```
Model:
```yaml
NormaTipo:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id_tipo:
              type: integer
            nm_tipo:
              type: string
      total:
        type: integer
      result:
        type: boolean
```

**Comment by umarley** [comment]
API revisada e documentação atualizada
