### ISSUE TITLE
Módulo normas - GET - Visualizar o PDF de uma norma

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#116]
![image](https://user-images.githubusercontent.com/45390353/187099539-4b92b578-22dc-4e01-90a4-0ba48d542397.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405/1/visualizar
Resultado:
•	Retorno do HTTP está 200 (OK)
•	Retorna o PDF
![image](https://user-images.githubusercontent.com/45390353/187099549-0d5fdce4-706a-44cd-8bea-f279bc5deee1.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405/0/visualizar
Resultado:
•	Retorno do HTTP está 200 (OK)
•	Como id não existe, não retorna nada
![image](https://user-images.githubusercontent.com/45390353/187099556-d480f6c3-0d0d-4724-bbe6-c1a035df26a2.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/5201405/0/visualiar
Resultado:
•	Retorno do HTTP está 404 – Not found
•	Não possui o retorno na documentação
![image](https://user-images.githubusercontent.com/45390353/187099564-739af1c7-8b75-4f80-a291-8c434eb1712f.png)

Exemplo de requisição:
GET https://sete.transportesufg.eng.br/normas/0/2/visualizar
Resultado:
•	Retorno do HTTP está 400 – Bad request
•	Não possui o retorno na documentação
•	Retorna o mesmo pdf para todos os ids
![image](https://user-images.githubusercontent.com/45390353/187099573-07f7efe8-ecd0-443d-a2d2-382fdeac9004.png)

**Comment by umarley** [comment]
API revisada e documentação atualizada
