### ISSUE TITLE
API requisita campos opcionais para cadastrar uma entidade aluno

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#13]
A API está requisitando campos opcionais (no caso o campo nome_responsavel). Favor verificar se está pedindo outros campos.

```json
{
    "nome": "AAAA",
    "data_nascimento": "10/10/1980",
    "sexo": 2,
    "cor": 1,
    "def_caminhar": "N",
    "def_ouvir": "N",
    "def_enxergar": "N",
    "def_mental": "N",
    "mec_tp_localizacao": 2,
    "turno": 2,
    "nivel": 1,
    "da_porteira": "N",
    "da_mataburro": "N",
    "da_colchete": "N",
    "da_atoleiro": "N",
    "da_ponterustica": "N",
    "loc_latitude": "-16.819554",
    "loc_longitude": "-49.246532",
    "grau_responsavel": 1
}
```

**Comment by umarley** [comment]
![image](https://user-images.githubusercontent.com/8119489/137403818-f1736692-789a-4f72-8057-b1c50fd44c03.png)

Este campo na documentação original do sistema está marcado como não nulo, inclusive na documentação do swagger ele esta marcado como obrigatório, portanto não vejo erro aqui.

O senhor deseja remover a obrigatoriedade do campo?
