### ISSUE TITLE
Erro na inserção de nova norma 

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#139]
O método POST não está funcionando adequadamente. Ao tentar entrar com os parâmetros abaixo ele menciona que não há o campo `outro_assunto` (que não é obrigatório).
Campos entrados:
* `titulo`: Teste da Norma
* `data`: 28/08/2022
* `tipo_veiculo`: 3
* `id_tipo`: 2
* `id_assunto[]`: 2
* `file`: arquivo pdf qualquer

![image](https://user-images.githubusercontent.com/1276322/188333060-f5bbac64-c806-4008-9bff-a34aac73ed01.png)

Se eu incluo o campo `outro_assunto` o erro persiste. (Lembrando que esse campo não é obrigatório).
```
    "detail": "Statement could not be executed (42P01 - 7 - ERROR:  relation \"normas.normas\" does not exist\nLINE 1: select max(id) as id from normas.normas n\n                                  ^)"
```

![image](https://user-images.githubusercontent.com/1276322/188333142-1dce6a26-1a7b-4f7d-a8cf-b70c7d3fb354.png)

**Comment by umarley** [comment]
@marcosroriz feito a correção no serviço. Fiz o teste aqui e funcionou corretamente. Teste por gentileza, caso o problema persista me avise.
