### ISSUE TITLE
Módulo Usuários - POST - Criar um novo usuário no municipio

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#141]
![image](https://user-images.githubusercontent.com/45390353/189025469-90d3f957-0b37-4004-bdf0-98b158bf5e8d.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405/ 
Body:
 {
        "nome": "João das Neves",
        "cpf": "02830357060",
        "telefone": "77991009100",
        "email": "joao-nevess@gmail.com",
        "password": "953414f9f1ed8dfe1798e518e7fe0468",
        "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 201 - Created
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "true", messages:{...} }
![image](https://user-images.githubusercontent.com/45390353/189025494-a548d7ca-339f-458b-a013-6e08c80db7e1.png)

•	Ao tentar novamente retorna:
{
    "result": false,
    "messages": [
        "O CPF informado já existe. Verifique e tente novamente!",
        "O Email informado já existe. Verifique e tente novamente!"
    ]
}

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/0 
Body:
 {
        "nome": "João das Neves",
        "cpf": "02830357060",
        "telefone": "77991009100",
        "email": "joao-nevess@gmail.com",
        "password": "953414f9f1ed8dfe1798e518e7fe0468",
        "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 403 - Forbidden
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189025573-66d47098-439a-4cac-8096-27cda07592c9.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/ste/5201405 
Body:
 {
        "nome": "João das Neves",
        "cpf": "02830357060",
        "telefone": "77991009100",
        "email": "joao-nevess@gmail.com",
        "password": "953414f9f1ed8dfe1798e518e7fe0468",
        "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 201 – Created
•	O link que coloquei foi errado e ainda assim retornou 201
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189025621-b7566426-c094-4a4c-ba50-f040c68c2573.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405 
Body:
 {
        "tipo_permissao": "admin"
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad Request
•	O link que coloquei foi errado e ainda assim retornou 201
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189025646-4f3021fe-3692-4329-8076-f0c3c33bc2d4.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405 
Body:
 {
        "nome": "João das Neves",
        "cpf": "02830357060",
        "telefone": "77991009100",
        "email": "joao-nevess@gmail.com",
        "password": "953414f9f1ed8dfe1798e518e7fe0468"
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad Request
•	O link que coloquei foi errado e ainda assim retornou 201
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189025675-76ae648b-72af-439f-953c-f024152ef27e.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
post:
      tags:
      - usuarios
      summary: Criar um novo usuário no municipio
      description: Este endpoint deve ser usado após o usuário esta autenticado.
      operationId: createUser
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        description: Código da cidade do usuário
        required: true
        type: integer
      - in: body
        name: body
        description: Created user object
        required: true
        schema:
          $ref: '#/definitions/Usuario'
      responses:
        201:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/CreateResponse'
        400:
          description: Parâmetros inválidos
        404:
          description: Recurso não encontrado
      security:
      - api_key: []
```

Model e response foram criados no primeiro POST

**Comment by umarley** [comment]
Documentação realizada
