### ISSUE TITLE
Módulo Usuários - POST - Atualizar a foto do perfil do usuário do sistema

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#142]
![image](https://user-images.githubusercontent.com/45390353/189025805-12afe5d2-3eb2-4ad4-bf99-aa5858034efa.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405/8051/foto
Resultado do experimento:
•	Retorno do HTTP é 201 - Created
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "true", “messages”:... }
![image](https://user-images.githubusercontent.com/45390353/189025882-eda13503-fd8e-467f-9c8b-5e586ca39659.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405/0/foto
Resultado do experimento:
•	Retorno do HTTP está 404 – Not Found
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”:... }
![image](https://user-images.githubusercontent.com/45390353/189025929-1d590b0b-c0eb-498c-913f-a3b28a51b9c0.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/sete/5201405/8051/fot
Resultado do experimento:
•	Retorno do HTTP está 404 – Not Found
•	O resultado não está na documentação da API
•	Está usando o seguinte formato 
{ result: "false", “messages”:... }
![image](https://user-images.githubusercontent.com/45390353/189025980-e5ca44b1-b85e-4418-910e-51eb5fcdfbe8.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/ste/5201405/8051/foto
Resultado do experimento:
•	Retorno do HTTP está 201 - Created
•	O resultado não está na documentação da API
•	Mesmo errando o link retorna created
•	Está usando o seguinte formato 
{}
![image](https://user-images.githubusercontent.com/45390353/189026016-0df965f0-0c71-4d7d-b07e-707355872a0e.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/ste/5201405/8051/foto
[foi enviado o campo Picture vazio]
![image](https://user-images.githubusercontent.com/45390353/189026056-48615499-3143-46ea-9ca6-3ccf53fabd6f.png)
Resultado do experimento:
•	Retorno do HTTP é 400 – Bad request
•	O resultado não está na documentação da API
•	Possui um resultado estranho com trechos de código
•	Está usando o seguinte formato 
{ result: "false", “messages”:... }
![image](https://user-images.githubusercontent.com/45390353/189026089-be83a4b6-656a-4453-a157-c4bee4f3fcd9.png)
 Ao desativá-lo retorna sem os códigos:
Body:
![image](https://user-images.githubusercontent.com/45390353/189026120-7aa09049-e2c0-4528-9fbd-841aaff21919.png)
Resultado:
{
    "result": false,
    "messages": "Campo picture vazio."
}

**Comment by umarley** [comment]
Operação realizada com sucesso
