### ISSUE TITLE
Módulo Escolas- POST - Incluir uma nova escola no sistema

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#143]
![image](https://user-images.githubusercontent.com/45390353/189026304-b4c70ac2-c68a-47da-944f-a463f5f71043.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/0 
Resultado do experimento:
•	Retorno do HTTP está 403 - Forbidden
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189026404-b2bfb950-b96f-4103-9168-f3a7b5af4cab.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405 
Body:
{
}
Resultado do experimento:
•	Retorno do HTTP está 400 – Bad Request
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "false", “messages”: ... }
•	Apenas retorna o erro nesses três campos, na documentação não informa quais são obrigatórios.
![image](https://user-images.githubusercontent.com/45390353/189026454-c31b87bb-7d94-4704-8f32-c4154bc2d3e8.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405 
Body:
{
}
Resultado do experimento:
•	Retorno do HTTP está 400 – Bad Request
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "false", “messages”: ... }
•	Apenas retorna o erro nesses três campos, na documentação não informa quais são obrigatórios.
![image](https://user-images.githubusercontent.com/45390353/189026519-48133d5c-e962-4022-a6af-30c55487475e.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405 
Body:
{
  "nome": "Colegio Municipal Padre Vieira",
  "mec_co_municipio": 2,
  "mec_tp_localizacao_diferenciada": 1
}
Resultado do experimento:
•	Retorno do HTTP está 400 – Bad Request
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "false", “messages”: ... }
•	Quando coloco apenas os dados que apareceu mensagem de erro retorna isso.
![image](https://user-images.githubusercontent.com/45390353/189026563-63239c96-d9c0-4a25-bd9e-8a7bc2cf866a.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405 
Body:
{
  "nome": "Colegio Municipal Padre Vieira",
  "mec_co_uf": 0,
  "mec_co_municipio": 2,
  "mec_no_entidade": "string",
  "mec_tp_dependencia": 1,
  "mec_tp_localizacao": 1,
  "mec_tp_localizacao_diferenciada": 1
}
Resultado do experimento:
•	Retorno do HTTP está 201 - Created
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "true", “messages”: ... }
•	Esses são os obrigatórios sem eles não consigo adicionar uma escola.
![image](https://user-images.githubusercontent.com/45390353/189026599-2c1c3af4-8336-4611-acfa-cb3d20943d74.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405 
Body:
{
  "nome": "Colegio Municipal Padre Vieira",
  "mec_co_entidade": 0,
  "mec_co_uf": 0,
  "mec_co_municipio": 2,
  "mec_no_entidade": "string",
  "mec_tp_dependencia": 1,
  "mec_tp_localizacao": 1,
  "mec_tp_localizacao_diferenciada": 1,
  "mec_in_regular": "S",
  "mec_in_eja": "S",
  "mec_in_profissionalizante": "S",
  "mec_in_especial_exclusiva": "S",
  "loc_latitude": "string",
  "loc_longitude": "string",
  "loc_endereco": "string",
  "loc_cep": "string",
  "contato_responsavel": "string",
  "contato_telefone": "string",
  "contato_email": "string",
  "horario_matutino": "S",
  "horario_vespertino": "S",
  "horario_noturno": "S",
  "ensino_superior": "S",
  "ensino_medio": "S",
  "ensino_fundamental": "S",
  "ensino_pre_escola": "S"
}

Resultado do experimento:
•	Retorno do HTTP está 201 - Created
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{result: "true", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189026641-70ddc2c2-6615-4acd-9110-404402976cdf.png)

**Comment by umarley** [comment]
Documentação atualizada
