### ISSUE TITLE
Módulo Escolas - POST - Associa vários alunos a uma escola

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#144]
![image](https://user-images.githubusercontent.com/45390353/189026774-05a99812-c5c7-49e9-a016-772a0b661ccf.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405/52278827/alunos  
Body:
{
  "alunos": [
    {
      "id_aluno": 0
    },
    {
      "id_aluno": 1
    },
    {
      "id_aluno": 2
    }
  ]
}

Resultado do experimento:
•	Retorno do HTTP está 200 – OK (não era pra ser created?)
•	Não está documentado na API
•	Está usando o seguinte formato 
{ ..., result: "true" }
•	Há vários campos NULL, verificar se é o correto com o Prof.  Marcos e o Umarley
•	Há campos do tipo _links, deve ser feito assim mesmo?
![image](https://user-images.githubusercontent.com/45390353/189026815-6b064263-ae53-496f-99de-a659446dbeec.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405/52278827/aluns  
Body:
{
  "alunos": [
    {
      "id_aluno": 0
    },
    {
      "id_aluno": 1
    },
    {
      "id_aluno": 2
    }
  ]
}

Resultado do experimento:
•	Retorno do HTTP está 404 – Not Found
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189026847-9284d987-bb4c-4d21-aa1f-2a985cbb20d3.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405/0/alunos  
Body:
{
  "alunos": [
    {
      "id_aluno": 0
    },
    {
      "id_aluno": 1
    },
    {
      "id_aluno": 2
    }
  ]
}

Resultado do experimento:
•	Retorno do HTTP está 404 – Not Found
•	Não está documentado na API
•	Escola não existe era para retornar erro e retornou em um formato estranho
![image](https://user-images.githubusercontent.com/45390353/189026914-2a1ca097-9298-4320-b2c5-f2748c71f0b7.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/0/52278827/aluns  
Body:
{
  "alunos": [
    {
      "id_aluno": 0
    },
    {
      "id_aluno": 1
    },
    {
      "id_aluno": 2
    }
  ]
}

Resultado do experimento:
•	Retorno do HTTP está 403 - Forbidden
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189026951-47cb9b10-e5a9-49a8-a939-e5b44828fa4a.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405/52278827/aluns  
Body:
{
  
}

Resultado do experimento:
•	Retorno do HTTP está 400 – Bad request
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{ result: "false", “messages”: ... }
![image](https://user-images.githubusercontent.com/45390353/189026986-f3167216-9573-4c08-94bc-12d1b12013c4.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/escolas/5201405/52278827/aluns  
Body:
{
    "data": [],
    "total": 0,
    "result": true
}

Resultado do experimento:
•	Retorno do HTTP está 200 - OK
•	Não está documentado na API
•	Está usando o seguinte formato 
•	{ result: "false", “messages”: ... }
•	Verificar se era para ter retornado algum tipo de erro.
![image](https://user-images.githubusercontent.com/45390353/189027016-845080a8-3f29-4c89-80ef-4715d4440aa2.png)

**Comment by nataliasou** [comment]
@umarley 
```yaml
post:
      tags:
      - escolas
      summary: Associa vários alunos a uma escola
      operationId: associarAlunoEscola
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: codigo_cidade
        type: integer
        description: Código da cidade do aluno a ser atualizado
        required: true
      - in: path
        name: id_escola
        type: integer
        description: ID da escola que os alunos serão associados
        required: true
      - in: body
        name: body
        description: JSON contendo os id's dos alunos  que serão associados
        required: true
        schema:
          $ref: '#/definitions/VariosAlunos'
      responses:
        201:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/CreateResponseVariosAlunos'
        400:
          description: Parâmetros inválidos
        404:
          description: Recurso não encontrado
      security:
      - api_key: []
```

Response:
```yaml
CreateResponseVariosAlunos:
    type: object
    properties:
      data:
        type: array
        items:
          type: object
          properties:
            id_aluno:
              type: string
            result:
              type: boolean
            messages:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
      result:
        type: boolean
```

**Comment by umarley** [comment]
Documentação atualizada
