### ISSUE TITLE
Criar endpoint  ​/escolas​/{codigo_municipio}​/{id_escola}​/rotas com os operadores GET/POST/DELETE

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#17]
O operador **GET** retorna um vetor com as rotas associada à aquela escola, incluindo o shape.
```json
[ { } , { }, {  }]
```

O operador **DELETE** apaga o vínculo das rotas com essa escola. Recebe como parâmetro o conjunto de rotas.
```json
[ 
    { "id_rota": 2 },
    { "id_rota": 10}
]
```

O operador ```POST``` vincula as rotas enviadas a escola do endpoint.
```json
[ 
    { "id_rota": 2 },
    { "id_rota": 10}
]
```

**Comment by umarley** [comment]
Endpoints já implementados.
