### ISSUE TITLE
Criar endpoint ​/rotas​/{codigo_municipio}​/{id_rota}​/escolas com os operadores GET/POST/DELETE

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#18]
O operador GET retorna um vetor com as escolas associada à aquela escola.

```json
[ 
  { 
    "id_escola": 12,
    "nome": "XYZ",
   } ,
  { }, 
  {  }
]
```

O operador DELETE apaga o vínculo da rotas com aquela escola. Recebe como parâmetro um conjunto de escolas.

```json
[ 
    { "id_escola": 2 },
    { "id_escola": 10}
]
```

O operador POST vincula a rotas com as escolas do endpoint.
```json
[ 
    { "id_escola": 2 },
    { "id_escola": 10}
]
```

**Comment by umarley** [comment]
Issue sendo tratada na  #Issue #48
