### ISSUE TITLE
Criar um campo optativo `outro_tipo_text` na tabela de veículos

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#184]
Campo optativo a ser criado e será recebido na requisição. 
Por padrão tem o valor NULO. 
Só terá valor caso o tipo seja OUTRO (= 15).

**Comment by umarley** [comment]
@marcosroriz feito, atualizado no ambiente de homologação api-qa.transportesufg.eng.br ... Assim que validado colocaremos em produção.
