### ISSUE TITLE
Endpoint /aluno/codigo_cidade/id_aluno/rota deve retornar array

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#185]
Atualmente o endpoint retorna nulo ou o objeto da rota que o aluno está vinculado.
Deve-se retornar um array com as rotas que ele esteja vinculado.

Nenhuma --> [   ] 
Uma --> [ {} ]
Duas --> [ {} , {} ]

**Comment by nataliasou** [comment]
@marcosroriz  Solicitação atendida, aberto o pull request para que o @umarley possa fazer a mesclagem com o master.
