### ISSUE TITLE
Criar endpoint ​/rotas​/{codigo_municipio}​/{id_rota}​/alunos com os operadores GET/POST/DELETE 

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#19]
O operador GET retorna um vetor com os alunos associada à aquela rota.

```json
[ 
  { 
    "id_aluno": 12,
    "nome": "XYZ",
   } ,
  { }, 
  {  }
]
```

O operador DELETE apaga o vínculo da rotas com aquele aluno. Recebe como parâmetro um conjunto de alunos.

```json
[ 
    { "id_aluno": 2 },
    { "id_aluno": 10}
]
```

O operador POST vincula a rotas com os alunos do endpoint.
```json
[ 
    { "id_aluno": 2 },
    { "id_aluno": 10}
]
```

**Comment by umarley** [comment]
@marcosroriz endpoints criados e documentados no swagger.
