### ISSUE TITLE
Criação de campos nos cadastros para Módulo Custos

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#20]
Na tabela motorista adicionar os seguintes campos:

| Nome da Variável | Tipo          | Exemplo | Unidade |
|------------------|---------------|---------| -----------| 
| salario          | DECIMAL(15,4) | 1257.03 | R$ |
| vinculo | INT | 1 - servidor efetivo, 2 - servidor comissionado, 3 - terceirizado , 4 - outro |   N/A | 

Na tabela veículo adicionar os seguintes campos:
| Nome da Variável  | Tipo          | Exemplo                                                                          | Unidade        |
|-------------------|---------------|----------------------------------------------------------------------------------|----------------|
| ipva              | DECIMAL(15,4) | 1257.03                                                                          | R$             |
| dpvat             | DECIMAL(15,4) | 592.01                                                                           | R$             |
| seguro_anual      | DECIMAL(15,4) | 2500                                                                             | R$             |
| consumo           | DECIMAL(15,4) | 10.5                                                                             | KM/L ou L/hora |
| tipo_combustivel  | CHAR          | * 'G' = Gasolina * 'D' = Diesel * 'E' = Etanol * 'N' = Gás Natural * 'O' = Outro | N/A            |
| numero_de_pneus   | INT           | 4                                                                                | N/A            |
| vida_util_do_pneu | DECIMAL(15,4) | 12                                                                               | KM             |
| preco             | DECIMAL(15,4) | 59999.20                                                                         | R$             |
| potencia_do_motor | DECIMAL(15,4) | 75                                                                               | cavalos        |

**Comment by umarley** [comment]
Tarefa concluida
