### ISSUE TITLE
Criação da entidade Monitor e seus endpoints PUT/POST/GET/DELETE e dos subendpoints GET/POST/DELETE de rotas

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#21]
Utilizaremos os seguintes campos:
| Nome da Variável | Tipo          | Exemplo                                                                       | Unidade                 |
|------------------|---------------|-------------------------------------------------------------------------------|-------------------------|
| nome             | VARCHAR       | Fulano da Silva                                                               | R$                      |
| cpf              | VARCHAR       | 0923818313                                                                    | N/A (sem char especial) |
| data_nascimento  | DATE          | 19/10/2020                                                                    | N/A                     |
| sexo             | INT           | 1 - M 2 - F 3 - N/I                                                           | N/A                     |
| telefone         | VARCHAR       | (62) 9348-4381                                                                | N/A                     |
| vinculo          | INT           | 1 - servidor efetivo, 2 - servidor comissionado, 3 - terceirizado , 4 - outro | N/A                     |
| salario          | DECIMAL(15,4) | 2000.00                                                                       | R$                      |
| turno_manha  | CHAR | 'S' ou 'N' | N/A |
| turno_tarde  | CHAR | 'S' ou 'N' | N/A |
| turno_noite  | CHAR | 'S' ou 'N' | N/A |

**Comment by marcosroriz** [comment]
Adicionar campos `loc_latitude` e `loc_longitude` como numéricos.

Campos obrigatórios:
`nome`, `cpf`, `data_nascimento`, `sexo`, `vinculo`, `turno_manha`, `turno_tarde`, `turno_noite`

Campos opcionais:
`telefone`, `salario`, `loc_latitude`, `loc_longitude`

**Comment by marcosroriz** [comment]
```json
{
    "nome": "Marcos Teste",
    "cpf": "49944398004",
    "data_nascimento": "12/01/1980",
    "sexo": 1,
    "turno_manha": "S",
    "turno_tarde": "N",
    "turno_noite": "N",
    "vinculo": 1,
    
    "telefone": "(62) 99210-5480",
    "salario": 1257.03,
    "loc_latitude": "-16.818333",
    "loc_longitude": "-49.246774"
}
```

**Comment by umarley** [comment]
Endpoints criados conforme solicitado. Já em produção!
