### ISSUE TITLE
Criação do relacionamento Monitor-Rota

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#22]
| Nome da Variável | Tipo | Exemplo | Unidade       |
|------------------|------|---------|---------------|
| codigo_cidade    | INT  | 5201415 | IBGE          |
| id_rota          | INT  | 2       | N/A (fk e pk) |
| id_monitor       | INT  | 4       | N/A (fk e pk) |

**Comment by umarley** [comment]
@marcosroriz associação criada e feita a implementação na API com os endpoints responsáveis por essa associação. Documentação disponível no swagger.
