### ISSUE TITLE
Criar estrutura da tabela de parâmetros

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#23]
| Nome da Variável    | Tipo    | Exemplo                                          |
|---------------------|---------|--------------------------------------------------|
| codigo_cidade       | INT     | 5201415                                          |
| codigo_parametro    | VARCHAR | ENCARGOS_SOCIAIS                                 |
| valor_parametro     | TEXT    | '20'                                             |
| descricao_parametro | TEXT    | Porcentagem de valores a serem pagos em impostos |

**Comment by marcosroriz** [comment]
|PARÂMETRO --> Encargos Sociais salário dos motoristas
|PARÂMETRO --> Coeficiente de custo de manutenção (RODOVIÁRIO)
|PARÂMETRO --> Coeficiente de custo de manutenção (AQUAVIÁRIO)
|PARÂMETRO --> VIDA ÚTIL (rodoviário)
|PARÂMETRO --> VIDA ÚTIL (aquaviário)
|PARÂMETRO --> VALOR RESIDUAL (rodoviário)
|PARÂMETRO --> VALOR RESIDUAL (aquaviário)
|PARÂMETRO --> TRC
|PARÂMETRO --> PREÇO médio do litro do combustível (diesel, gasolina, óleo e gás natural)
|PARÂMETRO --> COEFICINETE DE CONSUMO DE ÓLEOS E LUBRIFICANTES
|PARÂMETRO --> Número de recapagens
|PARÂMETRO --> COEFICIENTE DE CONSUMO DE PEÇAS E ACESSÓRIOS
|PARÂMETRO --> TAXA DE SEGURO DAS EMBARCAÇÕES (4.2%)
|PARÂMETRO --> TAXA ANUAL DE MANUTENÇÃO E REPARO DA EMBARCAÇÃO-TIPO
|PARÂMETRO --> DENSIDADE DE COMBUSTÍVEL (kg/litro)
|PARÂMETRO --> CONSUMO ESPECÍFICO DE LUBRIFICANTE (kg/hp)
|PARÂMETRO --> DENSIDADE DO LUBRIFICANTE (kg/litro)
|PARÂMETRO --> PREÇO médio do lubrificante (R$ / litro);

**Comment by umarley** [comment]
@marcosroriz tarefa concluída. 

https://app.swaggerhub.com/apis/umarley/SistemaSETE/1.0.0#/parametros
