### ISSUE TITLE
Localidades - GET: /localidades/municipios/{codigo}

### ISSUE THREAD

**Issue by irwinarruda** [umarley/seteAPI#24]
##  Explicação
O endpoint GET: /localidades/municipios/{codigo} não me retorna informações de identificação do município, em vez disso ele me retorna algumas informações de estado que não são tão necessárias. Segue um exemplo:
```json
    {
      "nm_cidade": "Tarauacá",
      "codigo_uf": 12,
      "estado": "Acre"
    },
    {
      "nm_cidade": "Xapuri",
      "codigo_uf": 12,
      "estado": "Acre"
    }
```

## O que é esperado
É esperado que o endpoint retorne algum identificador da própria cidade.

**Comment by umarley** [comment]
Bom dia @irwinarruda !

Solicitação atendida e já em produção.

'''json
 [
        {
            "nm_cidade": "Abadia de Goiás",
            "codigo_uf": 52,
            "codigo_cidade": 5200050,
            "estado": "Goiás"
        },
        {
            "nm_cidade": "Abadiânia",
            "codigo_uf": 52,
            "codigo_cidade": 5200100,
            "estado": "Goiás"
        },
        {
            "nm_cidade": "Acreúna",
            "codigo_uf": 52,
            "codigo_cidade": 5200134,
            "estado": "Goiás"
        },
        {
            "nm_cidade": "Adelândia",
            "codigo_uf": 52,
            "codigo_cidade": 5200159,
            "estado": "Goiás"
        }
]
