### ISSUE TITLE
Adicionar campo vinculo a entidade Motorista

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#25]
Adicionar o campo vinculo a entidade Motorista

| Nome da Variável | Tipo          | Exemplo                                                                       | Unidade                 |
|------------------|---------------|-------------------------------------------------------------------------------|-------------------------|
| vinculo          | INT           | 1 - servidor efetivo, 2 - servidor comissionado, 3 - terceirizado , 4 - outro | N/A                     |

**Comment by umarley** [comment]
@marcosroriz campo já adicionado no banco de dados e feita a implementação na API.
