### ISSUE TITLE
Operação DELETE escola de aluno não funciona

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#26]
Ao tentar realizar a operação de DELETE da escola de um aluno me deparo com a seguinte mensagem:

Requisição Enviada.
---------------------
**DELETE** https://sete.transportesufg.eng.br/alunos/5201405/3141/escola

```json
{
    "result": false,
    "messages": "Falha ao excluir o registro. Contacte o administrador do sistema para maiores informações. <br />SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at end of input\nLINE 1: ...digo_cidade =  '5201405' AND id_aluno = 3141 AND id_escola =\n                                                                       ^"
}
```

Resultado esperado, remover o aluno de sua escola caso tenha.

**Comment by umarley** [comment]
@marcosroriz  Feita a correção e já disponibilizado em produção.
