### ISSUE TITLE
Erros no endpoint Motoristas ao tentar cadastrar um novo motorista

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#27]
Quando envio um body vazio a API retorna a seguinte mensagem.

```json
{
    "result": false,
    "messages": {
        "nome": "O nome do aluno deve ser informado!",
        "data_nascimento": "O campo data de nascimento deve ser informado!",
        "data_validade_cnh": "O campo data de validade da CNH deve ser informado!"
    }
}
```
Veja que os campos estão com o texto de alunos e não motoristas.

Além disso, a API está exigindo o campo `data_validade_cnh` que não é obrigatório.
Os campos obrigatórios são:
`cpf, nome, data_nascimento, sexo, cnh, turno_manha, turno_tarde, turno_noite, tem_cnh_a, tem_cnh_b, tem_cnh_c, tem_cnh_d, tem_cnh_e`

Além disso, falta incluir também o campo optativo `ant_criminais` cujo valor é uma String.

**Comment by umarley** [comment]
@marcosroriz feita as correções devidas e já em produção...
