### ISSUE TITLE
Retorno do ID ao criar um elemento

### ISSUE THREAD

**Issue by irwinarruda** [umarley/seteAPI#29]
## Contextualização
Estou desenvolvendo a integração com a API no módulo de Alunos. Atualmente no SETE DESKTOP, ao cadastrar um aluno já existe a opção de o vincular a escolas e rotas como mostra na imagem abaixo.
<p align="center" width="100%">
    <img width="50%" src="https://user-images.githubusercontent.com/68255804/141833873-9d485760-6054-444d-a960-74d7e01239a0.png" />
</p>
Fica claro então, que no modelo que foi feito para o SETE API eu preciso cadastrar o Aluno primeiramente e depois o vincular com as escolas e as rotas. E realmente não há nenhum problema quanto a isso.

## Problema
Ao criar um aluno, percebi que recebo um json no seguinte formato:
```json
{
    "result": true,
    "messages": {
        "id": 11573
    }
}
```
Eu vejo essa resposta como algo problemático, pois na minha concepção o campo `messages` serve apenas para informar erros para o usuário. Inclusive o tratamento de erros está sendo feito contando com esse campo `messages` como o principal.

## Proposta
Com isso, gostaria de propor uma discussão sobre essa prática. É realmente necessário que seja assim? Qual seria uma outra forma de retornar essa informação?

**Comment by umarley** [comment]
@irwinarruda boa tarde!

Não entendi o problemático, pois realmente o campo `messages` tem essa função de retornar as mensagens de retorno da API. O que define se a requisição obteve sucesso ou não , não é a propriedade `messages` está com o valor preenchido, mas sim o código http da resposta bem como também a propriedade `result`. 

`result` == true -> Ok, sucesso
`result` == false -> Houve algum problema ou erro.

Neste caso do cadastro de aluno basta vc checar o valor de `result` sendo verdadeiro recupera o id em `messages.id` sendo falso exiba a mensagem `messages`.

Podemos sim marcar uma reunião para você me explicar melhor qual a problemática e se necessário, poderemos alterar a resposta desse end point e de todos os outros que seguem este mesmo padrão.
