### ISSUE TITLE
Operação GET da entidade motoristas ainda não foi implementada.

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#3]
O endpoint da API que recupera os motoristas (/motoristas/cod_cidade) retorna dados vazios.

![image](https://user-images.githubusercontent.com/1276322/135507877-1bbddb59-7d7e-4275-907a-63a2d748c367.png)

**Comment by umarley** [comment]
@marcosroriz professor, aqui acontece a mesma coisa quanto a listagem das rotas. No banco de dados não há motoristas cadastrados para a cidade informada.

**Comment by umarley** [comment]
@marcosroriz não temos o campo data_validade_cnh na tabela de motoristas. É para adicionar?

**Comment by umarley** [comment]
@marcosroriz Adicionado todos os campos.
