### ISSUE TITLE
POST: /alunos/{{codigo_cidade}}/{{id_aluno}}/escola

### ISSUE THREAD

**Issue by irwinarruda** [umarley/seteAPI#30]
## Explicação
Ao tentar vincular uma escola a um aluno, recebo um erro. Para reprodução, listarei os parâmetros que estou usando:

Request:
```json
{
    "Url": "/alunos/5201405/11576/escola",
    "Body": {
      "id_escola": 11020490
    }
}
```
Response: 
```json
{
    "result": false,
    "messages": {
        "nome": "O nome do aluno deve ser informado!",
        "data_nascimento": "O campo data de nascimento deve ser informado!",
        "nome_responsavel": "O nome do responsável pelo aluno deve ser informado!",
        "grau_responsavel": "Informe o grau de parentesco do responsável pelo aluno!"
    }
}
```

**Comment by umarley** [comment]
@irwinarruda requisição POST vincular escola a aluno testada e verificado que seu funcionamento está 100%.

![image](https://user-images.githubusercontent.com/8119489/149044529-bf020d69-08e1-4c3b-bf6a-9fc26a83403f.png)
