### ISSUE TITLE
POST: /alunos/{{codigo_cidade}}/{{id_aluno}}/rota

### ISSUE THREAD

**Issue by irwinarruda** [umarley/seteAPI#31]
## Explicação
O mesmo erro que acontece aqui, está acontecendo na issue #30 

Request:
```json
{
    "Url": "/alunos/5201405/11576/rota",
    "Body": {
      "id_rota": 3
    }
}
```
Response: 
```json
{
    "result": false,
    "messages": {
        "nome": "O nome do aluno deve ser informado!",
        "data_nascimento": "O campo data de nascimento deve ser informado!",
        "nome_responsavel": "O nome do responsável pelo aluno deve ser informado!",
        "grau_responsavel": "Informe o grau de parentesco do responsável pelo aluno!"
    }
}
```

**Comment by umarley** [comment]
@irwinarruda fiz uma requisição POST para o endpoint mencionado

/alunos/4203709/20/rota

e não tive esse retorno. Caso ainda continue este problema vamos marcar uma call.

**Comment by umarley** [comment]
Issue finalizada pela falta de retorno. Endpoint testado e o seu funcionamento está ok.
