### ISSUE TITLE
Criar endpoint para a API retornar os modelos dos veículos

### ISSUE THREAD

**Issue by umarley** [umarley/seteAPI#36]
Criar o endpoint /veiculos/modelos para retornar os modelos de veículos para o usuário poder selecionar no cadastro de veículo.

**Comment by umarley** [comment]
Endpoint criado, resta agora somente popular a tabela glb_modelos_veiculos

**Comment by umarley** [comment]
@marcosroriz anexe aqui por favor a imagem com o print da tela do trecho do select com os modelos de veículos por favor.

**Comment by marcosroriz** [comment]
```html
<select id="listamodelo" name="listamodelo" class="form-control">
<option value="0">Não se aplica</option>
<option value="1">ORE 1</option>
<option value="2">ORE 1 (4x4)</option>
<option value="3">ORE 2</option>
<option value="4">ORE 3</option>
<option value="5">ORE 4</option>
<option value="6">ONUREA</option>
<option value="7">Lancha a Gasolina</option>
<option value="8">Lancha a Diesel</option>
</select>
```

**Comment by umarley** [comment]
@marcosroriz tabela modelos populada com os seus devidos registros.
