### ISSUE TITLE
Erro ao vincular monitor em rota

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#41]
A requisição de vínculo a um monitor a uma rota retorna método não permitido (erro 405).

POST: https://sete.transportesufg.eng.br/monitores/5201405/49944398004/rota
Body: 
```json
{
    "id_rota": 8
}
```

Resultado esperado: vínculo do monitor 49944398004 com a rota 8

**Comment by umarley** [comment]
@marcosroriz problema resolvido. Teste por favor!
