### ISSUE TITLE
Ajustes na tabela de parâmetros

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#43]
descrição dos parâmetros todos em caixa alta
adição do campo valor_padrao
adição do campo descricao_detalhada

**Comment by marcosroriz** [comment]
Dê uma olhadinha novamente.

**Comment by umarley** [comment]
![image](https://user-images.githubusercontent.com/8119489/150182332-27fb5e40-92df-42b7-ae21-d2dd591b428d.png)


Verificado que os serviços dos parâmetros está 100%.
