### ISSUE TITLE
Ausência do endpoint `/rotas/{codigo_cidade}/{id_rota}/motoristas` e  `/rotas/{codigo_cidade}/{id_rota}/monitores`

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#47]
Fazer de forma semelhante aos endpoints de veículos da rota.

![image](https://user-images.githubusercontent.com/1276322/149982832-5403e888-a6d9-4402-a73b-af8120e6b964.png)

**Comment by umarley** [comment]
@marcosroriz quanto aos endpoints /rotas/{codigo_cidade}/{id_rota}/monitores , pois as demais requisições como POST e DELETE serão utilizadas /monitores/{codigo_cidade}/{cpf_monitor}/rota que atende o requisito do sistema.

**Comment by umarley** [comment]
@marcosroriz todos os endpoints para /rotas/{codigo_cidade}/{id_rota}/motoristas foi implementado.

Para o /rotas/{codigo_cidade}/{id_rota}/monitores foi implementado o método GET. Para os demais utilizar 

/monitores/{codigo_cidade}/{cpf_monitor}/rota
