### ISSUE TITLE
Ausência do endpoint `/rotas/{codigo_cidade}/{id_rota}/escolas`

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#48]
Semelhante ao issue #47 

![image](https://user-images.githubusercontent.com/1276322/150012943-43179fde-9fb6-4c48-b879-b72df201d514.png)

**Comment by umarley** [comment]
@JohnHeberty favor executar essa issue de acordo com o que combinamos.

A tabela responsável por armazenar o vinculo entre rota e escolas é sete_rota_passa_por_escolas. Vcoê pode olhar a implementação do vinculo entre rota e alunos que está na API.

**Comment by umarley** [comment]
@marcosroriz serviço executado.
