### ISSUE TITLE
Retornar o id da rota ao criá-la via POST (`/rotas/{codigo_cidade}`)

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#49]
Retornar o id da rota ao criá-la via uma requisição POST
```json
{
    "tipo": 1,
    "nome": "ROTA-1",
    "hora_ida_inicio": "10:00",
    "hora_ida_termino": "11:00",
    "hora_volta_inicio": "12:30",
    "hora_volta_termino": "12:55",
    "km": 144.44,
    "tempo": 90,
    "da_porteira": "S",
    "da_mataburro": "S",
    "da_colchete": "N",
    "da_atoleiro": "N",
    "da_ponterustica": "N",
    "turno_matutino": "S",
    "turno_vespertino": "S",
    "turno_noturno": "N"
}
```

**Comment by umarley** [comment]
@marcosroriz o retorno do ID já está implementado. O que acontece é que a sequence estava com um valor inferior ao número máximo de Id no banco de dados. Feita a correção na Sequence e agora está 100% o cadastro de novas rotas.

![image](https://user-images.githubusercontent.com/8119489/150182083-ba50a59f-0705-4591-8dcb-65ec317ed1be.png)
