### ISSUE TITLE
GET `/rotas/{codigo_cidade}/{id_rota}/motoristas` retorna 404 mesmo com dados válidos

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#51]
Requisição retorna 404 quando deveria retornar 200
GET `https://sete.transportesufg.eng.br/rotas/5201405/53383/motoristas`
![image](https://user-images.githubusercontent.com/1276322/150419040-48db12a8-8572-418d-a6e0-24f263d61cf9.png)

**Comment by umarley** [comment]
Resolvido
