### ISSUE TITLE
POST `/rotas/{cod_cidade}/{id_rota}/veiculos` indica que veículo não existe

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#52]
Favor verificar possível problema com o  endpoint, uma vez que está indicando que o veículo informado não existe.
Apesar disso, a operação GET `/veiculos/{cod_cidade}/` retorna o id indicado.

![image](https://user-images.githubusercontent.com/1276322/150419456-4353d7d7-8cab-4eba-92e4-95fe0be02945.png)

```json
{
    "id_veiculo": 96
}
```

Retorno:
```
{
    "data": {
        "result": false,
        "messages": "Veículo informada não existe!"
    },
    "total": 2,
    "result": false
}
```

**Comment by umarley** [comment]
@marcosroriz problema resolvido, favor testar!
