### ISSUE TITLE
Criar + QUATRO parâmetros global e renomear o PRECO_MEDIO_COMBUSTIVEL

### ISSUE THREAD

**Issue by umarley** [umarley/seteAPI#59]
PRECO_MEDIO_GASOLINA
PRECO_MEDIO_ETANOL
PRECO_MEDIO_DIESEL
PRECO_MEDIO_GNV
PRECO_MEDIO_OUTRO

**Comment by umarley** [comment]
@marcosroriz feito o ajuste necessário no endpoint de custos para que a API retorne o preco do combustivel de acordo com o cadastro do veiculo vinculado a rota.

**Comment by marcosroriz** [comment]
@umarley OK. Você chegou a fazer a atualização no endpoint `/parametros/{codigo_cidade}`?
No meu postman essa requisição não está retornando os parâmetros criados.

**Comment by umarley** [comment]
> p

Faltou excluir os registros no banco de dados para serem gerados novamente. Procedimento realizado.
