### ISSUE TITLE
Operação GET da entidade rotas não foi implementada

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#6]
O endpoint da API que recupera as rotas (/rotas/cod_cidade) retorna dados vazios.

![image](https://user-images.githubusercontent.com/1276322/135508519-6df2930d-59d0-43d4-87d5-fe9819a125fe.png)

**Comment by umarley** [comment]
@marcosroriz está implementada sim, acontece que a cidade qual você pesquisou não tem rota cadastrada para ela no banco de dados. Então será necessário fazer a requisição POST para cadastrar uma nova rota e ai depois fazer o GET.

**Comment by umarley** [comment]
@marcosroriz feito a carga de dados na tabela de rotas, favor verificar e me informar aqui quais os campos serão necessários serem adicionados.

**Comment by marcosroriz** [comment]
Oi @umarley, retornou direitinho.
Preciso dos seguintes campos no mínimo:

- nome
- turno_matutino
- turno_vespertino
- turno_noturno
- GPS (aí é verificar se o campo SHAPE está ou não vazio)
- km
