### ISSUE TITLE
Criar e testar a função de recuperação de senha

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#60]
No sentido de migrar a solução para o PostgreSQL,

Temos que prover a funcionalidade de recuperar senha.

**Comment by umarley** [comment]
@marcosroriz como faremos para validar o email do usuário uma vez que o sistema é desktop e não web?

Penso que no momento em que o usuário digitar o seu email e pedir para recuperar a senha, o sistema deva enviar um email com uma chave aleatória gerada onde o usuário deverá colar essa chave no campo solicitado e enviar a API para que a nova senha seja alterada.

**Comment by umarley** [comment]
Criado o serviço para recuperação de senha

https://app.swaggerhub.com/apis/umarley/SistemaSETE/1.0.0#/acesso/createLinkAccessRecovery
