### ISSUE TITLE
Criar estrutura para liberação de usuários

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#61]
Criar estrutura no banco de dados que possibilite liberar o usuário via SETE-FRONT.

**Comment by umarley** [comment]
@marcosroriz API refatorada, vai ser necessário alterar o front end para que possa funcionar a exclusão de usuários.

@irwinarruda favor alterar o metodo delete do endpoint 
https://app.swaggerhub.com/apis/umarley/SETE/1.0.0#/Permissão%20Firebase/delete_permissao_firebase__codigo_cidade___uid_

[/permissao-firebase/{codigo_cidade}/{uid}](https://app.swaggerhub.com/apis/umarley/SETE/1.0.0#/Permiss%C3%A3o%20Firebase/delete_permissao_firebase__codigo_cidade___uid_)

**Comment by marcosroriz** [comment]
@irwinarruda por favor dê uma olhada nisso

**Comment by umarley** [comment]
Problema já solucionado...
