### ISSUE TITLE
Ajustes nos valores default dos parâmetros

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#69]
Existe a necessidade de fazer alguns ajustes nos valores padrão dos parâmetros.

Segue os valores a serem utilizados:
COEFICIENTE DE CONSUMO DE ÓELOS E LUBRIFICANTES (L/KM) --> 0.05
CONSUMO ESPECÍFICO DE LUBRIFICANTE (KG/HP) --> 0.002
TAXA ANUAL DE MANUTENÇÃO E REPARO DA EMBARCAÇÃO-TIPO ---> 4

**Comment by umarley** [comment]
Valores ajustados.
