### ISSUE TITLE
Código gerado para recuperação é sempre o mesmo.

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#75]
Também observei que o código sendo gerado para recuperação de senha é sempre o mesmo.

![image](https://user-images.githubusercontent.com/1276322/152701042-bbf12fa8-0e29-4bbf-907e-0a7dea1adb19.png)

Att.,
Marcos Roriz

**Comment by umarley** [comment]
@marcosroriz conforme conversamos apesar dos caracteres serem parecidos, os códigos são diferentes.
