### ISSUE TITLE
Falha de segurana na API - SQL Injection

### ISSUE THREAD

**Issue by JohnHeberty** [umarley/seteAPI#81]
![image](https://user-images.githubusercontent.com/46422955/154722498-89722eb2-80d1-4941-aae8-389139407f00.png)

Hoje qualquer usuário com o e-mail de acesso sem a senha do usuário consegue efetuar o loguin via API usando SQL injection no compo da senha.

Código SQL que libera o acesso no compo da senha:    ' or '' = '

**Comment by JohnHeberty** [comment]
![image](https://user-images.githubusercontent.com/46422955/154724647-6876cba8-dc28-4fa3-acb8-260c1bc35653.png)

A falha também é valida para o campo de usuário, no qua da acesso ao 1° usuário do banco de dados.

**Comment by umarley** [comment]
@JohnHeberty problema resolvido John!
