### ISSUE TITLE
Inserir e Remover campos da tabela norma

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#92]
Remover campo `numero_norma` da tabela norma
Inserir o campo `data_registro` da norma (qndo a norma foi estabelecida pelo município)
![image](https://user-images.githubusercontent.com/1276322/182463673-b42e9303-1cef-464e-b052-90e756534423.png)

**Comment by umarley** [comment]
Solicitação atendida, adicionado campo data_norma e removido o numero_norma. Atualizado no swagger.
