### ISSUE TITLE
Campo Outros no cadastro de veículos

### ISSUE THREAD

**Issue by marcosroriz** [umarley/seteAPI#93]
Possibilidade #1 
Adicionar os tipos para o BD
```csv
is_rodo, is_aqua
s, s
n, n
s, s
```

**Comment by marcosroriz** [comment]
Possibilidade #2 
Tenho que também lidar com o caso em que o tipo outro (que seria is_rodo=S, is_aqua=S) e armazenar o texto.

**Comment by marcosroriz** [comment]
No post do veículo e no put teria um campo opcional 
```outro_texto```

**Comment by umarley** [comment]
Campo criado no banco de dados e serviço adapatado.
