### ISSUE TITLE
Módulo Usuários - GET - Obter os dados de um usuário específico

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#96]
![image](https://user-images.githubusercontent.com/45390353/187086159-78855665-5401-493c-86a0-3317b60a9fa4.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/sete/5201405/3920
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Os últimos quatro campos de cada usuário estão como NULL, verificar se é o correto com o Prof.  Marcos e o Umarley
![image](https://user-images.githubusercontent.com/45390353/187086175-31db572b-22cf-4991-b9d3-af34e93b2399.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/sete/5201405/0
Resultado:
•	Retorno do HTTP está 200 (OK)
•	O resultado está diferente do esperado na API
•	Está usando o seguinte formato 
{result: "true" }
•	O resultado retorna apenas true quando o id dado não existe
![image](https://user-images.githubusercontent.com/45390353/187086194-717f6992-c224-43d2-997e-9d0494714c19.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/sete/0/3920
Resultado:
•	Retorno do HTTP é 403 - Forbidden
•	A documentação não descreve como espera esse resultado
•	Está usando o seguinte formato 
{result: "false", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187086212-3e07d876-efc3-4020-9563-86750e9358e1.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/ste/5201405/3920
Resultado:
•	Retorno do HTTP é 404 – Not found
•	Não possui esse tipo de resultado na documentação
•	Está usando o seguinte formato diferente dos outros com quatro campos e um link, verificar se isso está correto com o professor.
![image](https://user-images.githubusercontent.com/45390353/187086225-5e6f0b64-dec0-4a23-8135-4fd6b479a28c.png)

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - usuarios
      summary: Obter os dados de um usuário especifico
      operationId: getUser
      produces:
      - application/json
      parameters:
      - name: codigo_cidade
        in: path
        description: Código do município
        required: true
        type: integer
      - name: id_usuario
        in: path
        description: ID do usuário que se deseja consultar
        required: true
        type: integer
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
              $ref: '#/definitions/DadosUsuario'
        400:
          description: Parâmetros incorretos.
        403:
          description: Usuário sem permissão para acessar o município selecionado.
        404:
          description: Recurso não encontrado.
      security:
      - api_key: []
    ```

**Comment by umarley** [comment]
API e documentação atualizadas.
