### ISSUE TITLE
Módulo Usuários - GET - Encerra a sessão do usuário

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#97]
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/users/logout
Resultado:
•	Retorno do HTTP está 200 (OK)
•	Não tem o resultado na documentação da API
•	Está usando o seguinte formato 
{ result: "true", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187086271-cf01369b-48a8-4c7c-a4d4-23f7f306e746.png)
Exemplo de requisição:
POST https://sete.transportesufg.eng.br/users/logout
Resultado:
•	Retorno do HTTP está 201 – Created, era para ter retornado method not allowed
![image](https://user-images.githubusercontent.com/45390353/187086285-baaaf904-4365-4813-af82-fbdf3a0f7940.png)

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - usuarios
      - authenticator
      summary: Encerra a sessão do usuário autenticado
      operationId: logoutUser
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/logout'
      security:
      - api_key: []
```

Modelo:
```
 logout:
    type: object
    properties:
      result:
        type: boolean
      messages:
        type: string
```

**Comment by umarley** [comment]
API e documentação revisadas
