### ISSUE TITLE
Módulo localidades - GET - Lista todos os estados brasileiros

### ISSUE THREAD

**Issue by nataliasou** [umarley/seteAPI#98]
![image](https://user-images.githubusercontent.com/45390353/187086578-916beb99-0e2d-409e-9e12-6ea7e82e2798.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/localidades/estados
Resultado:
•	Retorno do HTTP é 200 (OK)
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ ..., “total”: 0, result: "true" }
•	Os ids dos estados não seguem uma ordem e os nomes dos estados não estão em ordem alfabética, verificar se é assim mesmo.
![image](https://user-images.githubusercontent.com/45390353/187086667-3409dc1f-5013-4ce7-b735-21735db423af.png)
Exemplo de requisição:
GET https://sete.transportesufg.eng.br/localidades/estads
Resultado:
•	Retorno do HTTP é 404 – Not found
•	A documentação não possui resultado esperado
•	Está usando o seguinte formato 
{ result: "false", “messages”: “string” }
![image](https://user-images.githubusercontent.com/45390353/187086677-0c7ef1e3-031b-4fb9-afae-a3611d3cd33b.png)

Exemplo de requisição:
POST https://sete.transportesufg.eng.br/localidades/estados
Resultado:
•	Retorno do HTTP é 405 – Method not allowed
•	A documentação não possui resultado esperado
•	Não retorna nenhuma mensagem

**Comment by nataliasou** [comment]
@umarley 
```
get:
      tags:
      - localidades
      summary: Lista todos os estados brasileiros
      operationId: getAllEstados
      produces:
      - application/json
      responses:
        200:
          description: Operação realizada com sucesso
          schema:
            $ref: '#/definitions/allEstados'
        400:
          description: Parâmetros incorretos
        404:
          description: Recurso não encontrado.
```

Modelo:
```
allEstados:
    type: object
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/DadosEstados'
      total:
        type: integer
      result:
        type: boolean
  DadosEstados:
    type: object
    properties:
      codigo:
        type: integer
      nome:
        type: string
      uf:
        type: string
```

**Comment by umarley** [comment]
Documentação e API atualizadas....
